server:
  port: 8081
spring:
  data:
    mongodb:
      host: ${mongo.port.27017.tcp.addr:localhost} 
      port: ${mongo.port.27017.tcp.port:27017}
      database: personas
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.port.8761.tcp.addr:localhost}:8761/eureka/ 
