
server:
  port: 8888
  
  
spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/mjlopezca/GFT-CONFIG
               basedir: target/config
management:
  security:
    enabled: false               