spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.port.8761.tcp.addr:localhost}:8761/eureka/ 

zuul: 
 routes:
  public-restservice: 
   path: /public/**
   serviceId: persona-feing